export const projectData=[
   {
       id: 1,
       title: "AR WEBPAGE",
       description: "Designed a mock e-commerce web page utilizing the power of augmented reality (AR) to showcase three different products for a B2C Company of choice.",
       image: "",
       link: "",
       github:"",
       technologies:"HTML, CSS, JavaScript, SandBox, Modal Viwer Component npm package",
   },
   {
    id: 2,
    title: "BirdHouse",
    description:"A collobaritive project where we Developed a front-end webpage that allows users to search for birds and receive fun facts, bird sounds, and images via fetching to two remote repositories.",
    image:"",
    link:"",
    github:"",
    technologies: "HTML, CSS, JavaScript, Bulma",
},
{
    id: 3,
    title: "WeatherApp",
    description: "Simple weather application that allows a user to search for a city of their choice to be able to receive the current weather and a five day forecast. Utilizes an open WeatherApi to fetch data from.",
    image:"",
    link:"",
    github:"",
    technologies: "HTML, CSS, JavaScript",
},
{
    id:4,
    title:  "Portfolio",
    description:"My first Portfolio that showcases some of my earlier works. Utilize a free quote api that gives users who visist a boost of joy!",
    image:"",
    link:"",
    github:"",
    technologies:"HTML, CSS, JavaScript",
},
{
    id:5,
    title: "Social Network API",
    description:"A restful API for a social network application where users can share thoughts,react to friends thoughts, and create a friends list. This challenged me to grasp a nonSQL workflow when working on the backend.Utilized Insomia for testing all routes.",
    image: "",
    link:"",
    github:"https://github.com/Oscarl214/Social-Media-API",
    technologies:"NodeJs, MongoDb, Mongoose, Insomia",
},
{
    id:6,
    title: "Ecommerce Store",
    description:"Created a back end for a ecommerce store. This project challenged me to grasp a MySQL workflow. Utilized postman to test al routes.",
    image:"",
    link:"",
    github: "https://github.com/Oscarl214/Ecommerce_BackEnd",
    technologies: "Nodejs, Express, MySql, Sequelize",
},
{
    id:7,
    title: "GetFit",
    description:"A collobaritive project where we build a simple workout application that targeted beginners in the gym. We utilized the MVC paradigm framework to organize and modularize the codebase, while utilizing the handlebars.js library to create reusable templates for our pages.",
    image:"",
    link: "",
    github:"https://github.com/Sunny9810/Workout-App",
    technologies: "HTML, Bulma, Handlebars, MySQL, Bycript",
},
{
    id:8 ,
    title: "Cohort-Retort",
    description: "A collobarative project in which we created a social network application that was dedicated for our bootcamp cohort to use post bootcamp. This project challenged me to understand the MERN framework while also pushing myself to understand REACT and its state capabilities. I also learned how to implement my first SWS cloud service.",
    image:"",
    link:"https://cohort-retort-v1-3ead1d24c761.herokuapp.com/login",
    github:"https://github.com/Oscarl214/Cohort-Retort",
    technologies:"MongoDB, Express.js, React, Node.js,SWS S3 Service,GraphQL,Apollo Server Express,Bycript,Mongoose,TailwindCSS",
},
]